### ISSUE TITLE
TypeError: Object of type 'WebDriver' is not JSON serializable

### ISSUE THREAD

**Issue by MislavSag** [ad-m/python-anticaptcha#10]
I am not sure how can I combine you reCaptcha solver and selenium session. Fro example simple selenium code:
```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('http://www.hzzo-net.hr/statos_OIB.htm')
driver.find_element_by_id('upoib').send_keys('93335620125')
```
Now, I would like to execute reCaptcha part, but not sure how to do it. Itried for example:
```
api_key = xxxxx'
site_key = '6Lc3SAgUAAAAALFnYxUbXlcJ8I9grvAPC6LFTKQs'  # grab from site

client = AnticaptchaClient(api_key)
task = NoCaptchaTaskProxylessTask(driver, site_key)
job = client.createTask(task)
job.join()
print(job.get_solution_response())
```
But it returns an error in the title.
Not sure how to pass selenium session as input?

**Comment by ad-m** [comment]
Extract the site-key from the source code and only pass it and URL. The session does not matter. 

It will be something like that (I did not test it exactly). In case of any problems - it remains available. I am glad if you can integrate my library and use it.
```
import re
from selenium import webdriver

api_key = 'xxxxxxxxxxx'

driver = webdriver.Chrome()
driver.get('http://www.hzzo-net.hr/statos_OIB.htm')
driver.find_element_by_id('upoib').send_keys('93335620125')

url = driver.current_url
site_key = driver.find_element_by_class_name('g-recaptcha').get_attribute('data-sitekey')

client = AnticaptchaClient(api_key)
task = NoCaptchaTaskProxylessTask(driver, site_key)
job = client.createTask(task)
job.join()
response = job.get_solution_response()

driver.execute_script('document.getElementsByName("g-recaptcha-response")[0].text = "%s"' % (response))

time.sleep(1)

driver.find_element_by_tag_name('form').submit()

driver.close()
```

**Comment by ad-m** [comment]
It seems that the situation is a bit more complicated due to JS interaction. I will sit on it and present a solution today.

**Comment by MislavSag** [comment]
Yes, I have tried now and nothing happened.

**Comment by ad-m** [comment]
```
from selenium import webdriver
from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask
import os
import time

api_key = os.environ['KEY']

# Open web-browser
driver = webdriver.Chrome()
driver.get('http://www.hzzo-net.hr/statos_OIB.htm')
driver.find_element_by_id('upoib').send_keys('93335620125')

# Save required variables
url = driver.current_url
site_key = driver.find_element_by_class_name('g-recaptcha').get_attribute('data-sitekey')

# Send site-key to Anti-captcha
client = AnticaptchaClient(api_key)
task = NoCaptchaTaskProxylessTask(url, site_key)
job = client.createTask(task)
print("Waiting to recaptcha solution")
job.join()

# Receive response
response = job.get_solution_response()

# Inject response in webpage
driver.execute_script('document.getElementById("g-recaptcha-response").innerHTML = "%s"' % (response))

# Wait a moment to execute the script (just in case).
time.sleep(1)

# Press submit button
driver.find_element_by_xpath('//input[@type="image"]').click()

# driver.close()
```

It works for me. Please, verify the solution.

**Comment by MislavSag** [comment]
It works! Thanks a lot. When I watch what's happening in browser, i saw recaptcha iframe doesn't check that it is human. But anyway, it works :)

One more question
Is possible to hide ip (use proxies or VPI) inside ant-captcha services? Could you recommend solution?

**Comment by ad-m** [comment]
@MislavSag , I do not understand what communication with the Anti-captcha service you are talking about? 

To proxy communication:

- you <> website - setup a proxy eg. https://stackoverflow.com/questions/17082425/running-selenium-webdriver-with-a-proxy-in-python
- you <> anti-captcha - see example below,
- anticaptcha <> google - see example at https://github.com/ad-m/python-anticaptcha/blob/master/examples/funcaptcha.py (if more specific example do you need - let me know).

Example mentioned  above:
```
import requests

client = AnticaptchaClient(api_key)
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}

client.session = requests.Session(proxies=proxies)
```
I would like to point out that proxy communication of you <> anti-captcha makes no sense. Anti-captcha has information about your payment and is an entity in whose interest is not to reveal the identity of customers, so simply share such information will not. The VPN should work for you<>anti-captcha without additional configuration.
