### ISSUE TITLE
'Job' object has no attribute 'report_incorrect'

### ISSUE THREAD

**Issue by ConnorSMaynes** [ad-m/python-anticaptcha#15]
python 3.4

following one of the examples in README

code:

job.report_incorrect()

**Comment by ad-m** [comment]
@ConnorSMaynes , which version of python-anticaptcha do you use? Do you can provide ```pip freeze | grep 'anticaptcha'``` output? See https://github.com/ad-m/python-anticaptcha/blob/master/python_anticaptcha/base.py#L39 .

**Comment by ad-m** [comment]
@ConnorSMaynes , I suppose you're using an outdated library. Can you confirm? Can I close this issue?

**Comment by ConnorSMaynes** [comment]
Confirmed. I was using an older version from pip and not from GitHub.

**Comment by ad-m** [comment]
Latest version on pypi is v 0.3.1 . Version v 0.3.1 support ```job.report_incorrect()```.
