### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by encloinc** [ad-m/python-anticaptcha#2]
The recaptcha proxyless methods are returning an "answer hash".  My question is, what do I do with the answer hash for the captcha to be solved on the site? Do I make a request to Google's servers or something of the sort?  (Thanks for the help in advance)

**Comment by ad-m** [comment]
There is no need to requests to Google servers.

See [examples/recaptcha.py](https://github.com/ad-m/python-anticaptcha/blob/master/examples/recaptcha.py) for full integration example.

**Comment by ad-m** [comment]
If you mean a specific case - I can help solve it. Free in the repository or paid privately.

**Comment by encloinc** [comment]
The example works great, the problem is that the website i'm solving the recaptcha in requires a login, how would I go about doing this?

**Comment by encloinc** [comment]
I was gonna use the extension made for anti-captcha, but the problem with that one is that the website i'm using has a "Protected by recaptcha" box on the bottom left corner, and the extension solves it constantly using up my credits, im trying to figure out way to emulate the extension but for it to only solve once per page reload.

**Comment by ad-m** [comment]
Logging requires proper handling in a traditional way (this is independent of the presence or absence of captcha protection). See "[How to scrape a website that requires login with Python](http://kazuar.github.io/scraping-tutorial/)" and chapter "[Web Scraping](https://automatetheboringstuff.com/)" in Al Sweigart,Automate the Boring Stuff with Python: Practical Programming for Total Beginners

I do not know what extension you are talking about. This repository does not apply to any browser extension.

**Comment by encloinc** [comment]
Im talking about the extension on anti captchas webpage

**Comment by ad-m** [comment]
This repository does not apply to any browser extension, even the extension on anti-captchas webpage. It's out of scope of this repository.

In my opinion this issue was exhausted, so I close it.

**Comment by encloinc** [comment]
ouch
