### ISSUE TITLE
Looks like recaptcha.py doesn't work on Python 2.7

### ISSUE THREAD

**Issue by destroy** [ad-m/python-anticaptcha#20]
Subject, I keep getting:
Traceback (most recent call last):
  File "recaptcha.py", line 38, in <module>
    assert 'Verification Success... Hooray!' in process()
AssertionError

On Python 3.6 works fine.

**Comment by destroy** [comment]
Nvm, looks like they solving wrong sometimes?

**Comment by ad-m** [comment]
It all depends on the effectiveness of the Anti-captcha service. There is a risk of sending incorrect data to us.
