### ISSUE TITLE
API_KEY

### ISSUE THREAD

**Issue by aidamohamed** [ad-m/python-anticaptcha#24]
how can i get the API_KEY? please help me

**Comment by ad-m** [comment]
Go to http://getcaptchasolution.com/i1hvnzdymd , register, login and go to settings. If you have any questions - just ask more.

**Comment by ad-m** [comment]
Did you get the API key?

![obraz](https://user-images.githubusercontent.com/3618479/49319362-c04ce180-f4fc-11e8-8bca-2b6ee1c2dae4.png)

**Comment by ad-m** [comment]
Closed due inactivity.
