### ISSUE TITLE
reCaptcha Selenium not verifying

### ISSUE THREAD

**Issue by SamuelLopesSilva** [ad-m/python-anticaptcha#27]
I'm using Selenium / Python to fill out a form, however, I get the answer from the solution but nothing happens in the captcha. I've read both Issues that talk about Selenium integration and tried to use all the codes, but none worked. Can you help me?

site: https://www63.bb.com.br/portalbb/djo/id/comprovante/consultaDepositoJudicial,802,4647,4650,0,1.bbx

![image](https://user-images.githubusercontent.com/42854396/55631816-4620b800-578f-11e9-8271-d212cdd9e54a.png)

**Comment by ad-m** [comment]
Thank you for your message. I will have a look at it at the weekend!

**Comment by ad-m** [comment]
@SamuelLopesSilva ,could you provide any valid value for that form?

**Comment by SamuelLopesSilva** [comment]
Try: 081110000004878936

**Comment by ad-m** [comment]
Here is code for you: https://gist.github.com/ad-m/3f020544553c09a4063e1aab24c8e9ff
Let's me know if it works for you.

Recognizing the need for constant support for Selenium, I started working on an example of using a library from Selenium, which I will regularly test to ensure constant and correct operation.

**Comment by SamuelLopesSilva** [comment]
Thank you! As soon as I get home I'll test and let you know if it worked.

**Comment by ad-m** [comment]
BTW. Why do you want to use Selenium for scraping that website? Any XML parser should be enought & lot faster.

**Comment by SamuelLopesSilva** [comment]
I'm newbie and had a very tight deadline. Anyway, I accept tips and help

**Comment by SamuelLopesSilva** [comment]
@ad-m It worked! Thank you a lot!

**Comment by ad-m** [comment]
For anybody which may it concer I added constatly-tested example how to use ```python_anticaptcha``` and ```selenium``` together: https://github.com/ad-m/python-anticaptcha/blob/master/examples/recaptcha_selenium.py
