### ISSUE TITLE
Too long responds

### ISSUE THREAD

**Issue by OmerBenGera** [ad-m/python-anticaptcha#28]
When trying to solve the recaptcha "I am not a robot", I receive too long responses and I am pretty sure these tokens are invalid.
Maybe I am wrong, but I am pretty sure that's the issue. Here is the code I am using:
https://pastebin.com/cBjzcRN1

**Comment by ad-m** [comment]
> Google lately increased average recognition time for their Recaptchas for more than 2 times. This issue affected not only our workers, but everyone who uses internet and encounters recaptcha on their way. Yes, we all hate it.
> Some websites allow only 30-50 seconds to fill their forms and for such cases we have a solution which exists thankfully to the flawiness of Recaptcha itself. It actually was there before, but this time we've made a graphical representation for better understanding.

See https://anti-captcha.com/clients/help/fastrecaptcha for workaround. 

If the information provided turns out to be insufficient - let me know, I will try to help you more.

**Comment by OmerBenGera** [comment]
@ad-m I changed the code so first I get the captcha respond, then I send a GET packet to the website, then I sumbit the captcha - and it fails. Here is my code:
https://pastebin.com/92z3AvHm

**Comment by ad-m** [comment]
I will look at that today or tomorrow.

**Comment by ad-m** [comment]
I tried to log in to the website more than 20 times. Unfortunately, I have not received a captcha in any case. Could you send me eg.via mail account access data, which is verified in the scope of captcha, because - apparently - this issues does not apply to all accounts.

**Comment by OmerBenGera** [comment]
@ad-m What's your email? I'll send you login details to my windows server

**Comment by ad-m** [comment]
@OmerBenGera: my e-mail is following:
```
OmerBenGera@jawnosc.tk
```

**Comment by ad-m** [comment]
The issues occurs outside of the library in a specific environment and the way the user uses it.
