### ISSUE TITLE
Again Integrating selenium/not submitting form

### ISSUE THREAD

**Issue by MacMarde** [ad-m/python-anticaptcha#37]
I am sorry for the duplicate. I already posted in the closed issue #19 
But I am not sure if anyone read it, because its closed.

So here again:

@ad-m
I really tried hard using your code with selenium and chrome.
I want to login on https://www.swagbucks.com/p/login
![grafik](https://user-images.githubusercontent.com/50266741/60145583-cc64fd00-97c6-11e9-9c72-9c9e9e739a8b.png)

I can't get it working. I am getting following error message:

```
in process token = get_token(url, site_key, invisible_captcha) 
in get_token is_invisible=invisible
TypeError: __init__() got an unexpected keyword argument 'is_invisible'
```

is_invisible is set to True globally. Changing it to False or removing it does also not work.
Please help me. I really have no idea what I am doing wrong.

**Comment by MacMarde** [comment]
It is working if I am removing is_invisible like this:

```
def get_token(url, site_key):
    task = NoCaptchaTaskProxylessTask(
        website_url=url,
        website_key=site_key
    )
    job = client.createTask(task)
    job.join()
return job.get_solution_response()
```

But now I am getting another error from:

```
 form_submit
 driver.execute_script("onSuccess('{}')".format(token))
```

with the error:
`selenium.common.exceptions.JavascriptException: Message: javascript error: onSuccess is not defined``

Any ideas?

I also tried the following:

```
driver.execute_script('document.getElementById("g-recaptcha-response").innerHTML = "%s"' % token)
time.sleep(1)
driver.find_element_by_xpath('//button[@type="submit" and @class="btn-std"]').click()
```

But I again got an error code saying:
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@type="submit" and @class="btn-std"]"}`

I tried using XPathHelper to get the XPath from the submit button, but XPathHelper won't work with this button.

I have tried this solution I have found on stackoverflow:

```
driver.execute_script('document.getElementById("g-recaptcha-response").innerHTML = "%s"' % token)
    time.sleep(1)
    frame1 = driver.find_element_by_xpath(".//iframe[@title='recaptcha challenge']")
    driver.switch_to.frame(frame1)
    driver.find_element_by_xpath(".//*[@id='recaptcha-verify-button']").click()

```
With this method the recaptcha submit button gets clicked, but then the recaptcha frame just says "Please select all matching images." So the recapthca is not solved.

**Comment by MacMarde** [comment]
I am also not sure if I do have the correct site-key.
I cant find an entry like:
`<div class="g-recaptcha" data-sitekey="6Lc_aCMTAAAAABx7u2W0WPXnVbI_v6ZdbM6rYf16"></div>`

I also cant use firebug to find it, because firebug is no longer available. With Firefox Developer its also not working because I never get a google captcha. And firebug with chrome is also not working because I cant see the traffic. Why is there no applicable solution documented?

I can only find this with chrome Developer Tools:

```
var welcomeVid = "//www.youtube.com/embed/0z96q2Aixig?rel=0&autoplay=1&wmode=opaque";
            sbGlbl.loginLp = sbGlbl.loginLp();
            sbGlbl.loginLp.onResizeRunner();
            $(window).bind('resize', sbGlbl.loginLp.onResizeRunner);
            sbGlbl_IsLoginLanding = true;
            sbGlbl.captchaRequired = true;
            sbGlbl.captchaSitekey = '6Ld48JYUAAAAAGBYDutKlRp2ggwiDzfl1iApfaxE';
```

This is the best I can get. I hope its the correct site key. Any help appreciated.

**Comment by ad-m** [comment]
![obraz](https://user-images.githubusercontent.com/3618479/60234272-c4c75600-98a3-11e9-9258-ff4ed80f2f46.png) from https://app4-cdn2.sbx-cdn.com/content/components/login-form/login-form.pmin.js?v=1035533-438a .

Site-key which you should provide is ```6Ld48JYUAAAAAGBYDutKlRp2ggwiDzfl1iApfaxE```.

**Comment by ad-m** [comment]
> TypeError: __init__() got an unexpected keyword argument 'is_invisible'

Which version of library do you use? That parameter was introduced first time in 0.3.2 . You should use the library at least in version 0.3.2 to be able to properly resolve this captcha.

**Comment by ad-m** [comment]
>  selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@type="submit" and @class="btn-std"]"}

To select button you can use following xpath:
```
//*[@id="loginBtn"]
```

**Comment by MacMarde** [comment]
@ad.m I am using v. 0.3.1 which is the latest version from pip.
But its working when I just delete the is_invisible parameter as I wrote above.
I am also getting a token.

Your site key is also the same key I do use. I dont know how to use the code and link you posted. The website from the link is not displayed correctly.

As I wrote I think I am able to click the button now. But nothing happens. The recaptcha frame just tells me "Please select all matching images."
With your Xpath I get the following error: 
`Message:` no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='loginBtn']"}   

Maybe I don't understand how to use your code.
I am able to get a token. I can see it in the comman line window. But what should I do now with the token? How to use the token to bypass the displayed Recaptcha?

**Comment by ad-m** [comment]
Here is script for you problem:
```
import re
from os import environ

from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask

api_key = environ['KEY']
invisible_captcha = True
url = 'https://www.swagbucks.com/p/login'
client = AnticaptchaClient(api_key)


def get_token(website_url, site_key, invisible):
    task = NoCaptchaTaskProxylessTask(
        website_url=website_url,
        website_key=site_key,
        is_invisible=invisible
    )
    job = client.createTask(task)
    job.join()
    return job.get_solution_response()


def process(driver):
    driver.get(url)
    site_key = re.search("captchaSitekey = '(.+?)'",driver.page_source).group(1)
    print("Found site-key", site_key)
    print("Send challenge")
    token = get_token(driver.current_url, site_key, invisible_captcha)
    print("Received challenge-response")
    driver.find_element_by_xpath('//*[@id="sbxJxRegEmail"]').send_keys('email@test.com')
    driver.find_element_by_xpath('//*[@id="sbxJxRegPswd"]').send_keys('password')
    driver.find_element_by_xpath('//*[@id="loginBtn"]').click()
    print("Form submitted")
    driver.execute_script("document.getElementById('g-recaptcha-response').innerHTML='{}';".format(token))
    driver.execute_script("document.getElementById('loginForm').submit()")
    return driver.find_element_by_xpath('//*[@id="divErLandingPage"]').text


if __name__ == '__main__':
    from selenium.webdriver import Firefox
    from selenium.webdriver.firefox.options import Options

    options = Options()
    # options.add_argument('-headless')
    driver = Firefox(firefox_options=options)
    assert 'Incorrect Email/Password Combination' in process(driver)
```
It requires the latest version of the library that I will release today on pypi (or you can fetch from repository).

**Comment by MacMarde** [comment]
@ad-m Thank you very much. Thats really great. I will try it soon.

At the moment I have found another solution:
I have installed the Antcpt chrome crx plugin with the selenium command:

`options.add_extension("extensions/AntiCaptcha/anticaptcha-plugin_v0.3101.crx")`

After the plugin is loaded I can configure it over the app API with executing JavaScript, something like:

```
script = "window.postMessage({receiver: 'antiCaptchaPlugin', type: 'setOptions', options: {antiCaptchaApiKey: '1234567890', autoSubmitForm: true,	saveInStorage: true}}, window.location.href);"
browser.execute_script(script)
```
Its working so far, but I am not sure if its working reliable. The first testing was inconsistent.  

I guess your solution is better. I need to test it soon.

**Comment by ad-m** [comment]
I will gladly provide all necessary support. Let me know if you experience any difficulties.

**Comment by MacMarde** [comment]
@ad-m I have tested your code and its working like a charm.
Only the following XPath element can not be found:

`return driver.find_element_by_xpath('//*[@id="divErLandingPage"]').text`

but I guess this is not important and is only a code line to check if login was successfull. There might be also other ways to check that.

**Comment by ad-m** [comment]
That line of code is only for validate result of form submission. You can handle that in different way according to you needs.

Is there any other missing integration which do you need? Could you close that issue if there is nothing to add?

**Comment by MacMarde** [comment]
Ok thanks again. I close the issue.
