### ISSUE TITLE
Extract sitekey with python using re.search

### ISSUE THREAD

**Issue by MacMarde** [ad-m/python-anticaptcha#39]
@ad-m 
Hi Adam, you already helped me a lot integrating your python code to use with selenium/chrome.

Now I do have another recaptcha, where I am not able to handle it.

First of all I am trying to extract sitekey. This was your code for the last recaptcha:

`site_key = re.search("captchaSitekey = '(.+?)'",driver.page_source).group(1)`

I dont understand how to use the re.search. It's really difficult for me to understand the syntax.
But I guess this time its more complicated, because the sitekey can not be found in the page_source.
Take a look here:

![grafik](https://user-images.githubusercontent.com/50266741/60452746-8927e580-9c2f-11e9-96fa-5979535b704a.png)

It seems like "sitekey" is inside of a javascript function.
I hope you will help me again.

**Comment by ad-m** [comment]
I am out of office, but small help.

Here is regexp tutorial: https://medium.com/factory-mind/regex-tutorial-a-simple-cheatsheet-by-examples-649dc1c3f285

Regexp is about how to extract data from text. 

Could you provide me link to that page & how to trigger recaptcha?

**Comment by MacMarde** [comment]
There is a very long link, but its surely temporarily and its identifiable. I hope I don't get blocked on the site for posting it here. 

I post it [here](https://adserver.entertainow.com/zmgzpn.html?s=enc&rid=-502853179$154368999$vpj2QVo1SbPSpZhcqLWcKA&hsh=a705c915efcf57321a9c584ec750b03b7cf4a07a822497de6f52dddd4d1f4545&uid=58368914&sn=32768&returnUrl=https%3A%2F%2Fpf.entertainow.com%2Ff%2Fp%2Fenter%3Fplid%3D5b20522f7591fdc1418b4568%24154368956%24jPJ*pdhbyWqYdXEjWpMD.w%26euid%3D5d16abe7d50308a73e35ca76%24154368956%24oytInltQjMOz36lDm6Tt5A%26rock%3D%257B%2522fid%2522%253A%2522561544a67591fda2598b4567%2522%252C%2522puid%2522%253A%252258368914%2522%257D%26paper%3Dpq4pNV2wBaQ6jy6jsg29qWKIWEM2lgnVzrnOftOWOtWLfKu1CTN7vMxoYDsQRVETJg0UuF38SfDsIw2z8klV951ItmelQ_dXvPhNXQ5wPJkcHsRtSfXpeVzghsV3q6vjhnHVJDRu6CHuLhcGm95QPrn9VV88dpdhWDZUbUCxS7gmDAKzvc-9jeTNT4pyUd-cZRcA3Fw--6u68SRB5MdJLrhnHa8A7i_Hraya4skuUvYVw_lmT6G_MFpqCh5H-a63hxna8PotM5E%26hasRedesign%3D0%26urrMet%3Dnull%26sig%3D4026719678a6045a7f2e054c2bd1f7ee%26encl%3D370900474%26trkid%3D1108961&iasHash=OPDBQgYbFckkA3it6WJ/iQ==&forensiqHash=572919d4acd58ea12e0124b4ba4c5327&encl=370900474&plid=5b20522f7591fdc1418b4568&fid=561544a67591fda2598b4567):

I don't know how long the link will be valid. I have tried it to open with different browser and IPs and seems to work for now.

**Comment by ad-m** [comment]
See there: https://github.com/ad-m/python-anticaptcha/pull/38/commits/a41133985e07eb695011bdab8c95932cddf6195a :smiley_cat:

**Comment by MacMarde** [comment]
Wow thats fantastic. Thank you very much. I could not have done this. You are a python genius.

I will test it soon and let you know if its working for me.

**Comment by MacMarde** [comment]
I justed wanted to test your code. But my account got banned. That is what I was afraid of. Propably no good idea to click this temporarily recaptcha link from different IP locations.
It is no problem I will make a new account and test it.

**Comment by ad-m** [comment]
Is there anything what I can do for you?

**Comment by MacMarde** [comment]
@ad-m 
No thank you. I am still testing. Until now with the new account the recaptcha did not appear again.
I will let you know if its working when the captcha appears again.

**Comment by MacMarde** [comment]
@ad-m 
I need your help again. I have tested it but the captcha is not solved.
The sitekey extraction is working fine and I am also getting a valid token. 
Also the Javascripts are executed and everything is running without errors. But the recaptcha just does not disappear. It seems like the site just gets reloaded and the recaptcha just reappears.
Where in your code gets the check box clicked? Or is this not neccessary?

**Comment by ad-m** [comment]
There is no need to get checkbox clicked. I call callback function for form submission.

Could you anyway provide new URL to verify what is missing?

**Comment by MacMarde** [comment]
I now completely observed the process. It seems like the site won't reload, instead just nothing happens.
In debug I can see everything looks good (sitekey, token, no exceptions) but it is not going on. Also on my Anticaptcha Dashboard History window I can see some solved "I'm not a robot" recaptchas. So it seems like everything is working, but the recaptcha is not submitted.
I will post the URL if I see the recaptcha again. I need to restart now and check. 
I am running selenium chrome with proxy. Maybe it would be a good idea if you test it with the same proxy (at least my account probably don't gets banned again this way)? I don't know if you want to or if it makes sence but if you want just give me your IP so I can add your IP to the authorized IPs of my proxy service provider.

**Comment by MacMarde** [comment]
New linke [here](https://adserver.entertainow.com/zmgzpn.html?s=enc&rid=-1439754427$154558298$p.256mpryEGNx3U81zmoeg&hsh=e4975ca16f01293633e43a72754e77e5940256a7099c62407d03fbdf26a527b7&uid=58451641&sn=32768&returnUrl=https%3A%2F%2Fpf.entertainow.com%2Ff%2Fp%2Fenter%3Fplid%3D5ad8fe3f7591fd6b028b456a%24154558258%24V7adDOCkmN*ZUvGB.1.2ew%26euid%3D5d1a9d9e22ddea65e0ecd58c%24154558258%24GsIJnZTJ*E6vD.QK5lEf9A%26rock%3D%257B%2522fid%2522%253A%2522561544a67591fda2598b4567%2522%252C%2522puid%2522%253A%252258451641%2522%257D%26paper%3DUkiES138wleGYa8gl2EP8ZttqoQll52kK1FqJA2Y1SHKh-r8CTZfMqUrhgPpv12ixQ53_-2O3Uv2vYVBR6NXOkyCOuq7R3emsEH7x7DnrMjgojMFS1ysh02ZfxM4rQQa8UhcxlnnmievnXl55dESErXQ787HwIjkQIRbEZXxm1Dj-08FjIjj0_4vrt8Bv3BkTV3cDIvpPmxIna7TA-WFdEuMsy5ioNqwkYvgpRiG951ysEnXIr6wX1954G82b9FoCqLhc8EiM14%26hasRedesign%3D0%26urrMet%3Dnull%26sig%3D17f2ef9c4adafc9197193b31e502992f%26encl%3D290993138%26trkid%3D1073418&iasHash=+ItA3q3JTQkAgeMnWXbCMA==&forensiqHash=a6401be5c80d600d52eee660ec53ef95&encl=290993138&plid=5ad8fe3f7591fd6b028b456a&fid=561544a67591fda2598b4567)

If you don't want to use proxy or you don't think it makes sence just use the link like you want, else just give me you IP.

**Comment by MacMarde** [comment]
@ad-m What do you think? Any progress?

**Comment by MacMarde** [comment]
I am testing atm. It seems like there are more than one recaptcha. This means my program needs to solve multiple recaptchas in a while loop until the recaptchas disappear. Could this be?

**Comment by ad-m** [comment]
Today I can not take care of it. It is possible that there are many captcha images. I'll take care of it during the weekend.

**Comment by MacMarde** [comment]
Ok let me know if you need a new link. Might be the link is not valid any more.

I have tried to get behind the recaptcha. Im not sure if its working. I am getting upto  4 recaptchas in one row. Site is relaoding each time after captcha is solved by your code, but either the next same recaptcha appears or an error message from the website entertainow.com . The error message is not from google, so I really don't know if its working or not. 
I will try it again today. Maybe I can get behind the recaptchas. 
I am waiting for your help on weekend.

**Comment by MacMarde** [comment]
Just to keep you updated:
I have tried to solve captcha with your code about 30 times. It was not working.
Now I did let the chrome extension from Anticaptcha solve the recaptcha and it was directly working with the first recapctha. 
One difference I have noticed: After the extension solved the recaptcha a blue check appeared in the check box, like it has been clicked. In your code no blue chechk appears.
So now we know your code is not working for me. But I still would prefer your code if possible, because its a cleaner solution I guess. I believe the problem happens with the submitting of the token.

**Comment by MacMarde** [comment]
Maybe instead of a working code solution I would also be glad if you can give me informations about how I can find out how to do it on my own.
What are the basics? Is there a good documentation with examples anywhere? I understand that I do have to inject the token somwhere in the HTML code and send it back to google somehow. This is what the javascript functions do. But how to find out where to inject and which function to call?

**Comment by ad-m** [comment]
>  What are the basics? Is there a good documentation with examples anywhere? I understand that I do have to inject the token somwhere in the HTML code and send it back to google somehow. This is what the javascript functions do. But how to find out where to inject and which function to call?
I set these values based on a thorough tracking of JavaScript code. It requires knowledge of JavaScript.

> Would be nice if you could use my proxy to test it.

92.222.22.91

> After the extension solved the recaptcha a blue check appeared in the check box, like it has been clicked. In your code no blue chechk appears.

It's just a form of presentation. It does not affect the way of communication with the server and the operation of the target server.

>  I am getting upto 4 recaptchas in one row. Site is relaoding each time after captcha is solved by your code, but either the next same recaptcha appears or an error message from the website entertainow.com 

Multiple captcha in a row support in the given example script is not supported. I am not able to obtain such a situation on any of the given links, hence I am asking for information on obtaining fresh addresses using your proxy. My VPN IP address is above.

**Comment by MacMarde** [comment]
Thanks for your answer.

As I wrote you there are not really multiple captchas in one row. They only reappear because soving with your code did not work. The same captcha was solved on the first try with the antcpta chrome extensions.

At the moment I don't have any captchas to send you a link. I need to turn off antcpta chrome extension and wait for a new recapthca to appear. I will send you the link once it appears again and give you the proxy IP.

**Comment by MacMarde** [comment]
One thing I have thought about:
Could it be this line of code has one comma too much:
`callback_function = re.search('(CAPTCHA_IMMEDIATE.+?),', driver.page_source).group(1)`

whats about (one comma removed)?: 
`callback_function = re.search('(CAPTCHA_IMMEDIATE.+?)', driver.page_source).group(1)`

**Comment by MacMarde** [comment]
> 
> 
> New linke [here](https://adserver.entertainow.com/zmgzpn.html?s=enc&rid=-1439754427$154558298$p.256mpryEGNx3U81zmoeg&hsh=e4975ca16f01293633e43a72754e77e5940256a7099c62407d03fbdf26a527b7&uid=58451641&sn=32768&returnUrl=https%3A%2F%2Fpf.entertainow.com%2Ff%2Fp%2Fenter%3Fplid%3D5ad8fe3f7591fd6b028b456a%24154558258%24V7adDOCkmN*ZUvGB.1.2ew%26euid%3D5d1a9d9e22ddea65e0ecd58c%24154558258%24GsIJnZTJ*E6vD.QK5lEf9A%26rock%3D%257B%2522fid%2522%253A%2522561544a67591fda2598b4567%2522%252C%2522puid%2522%253A%252258451641%2522%257D%26paper%3DUkiES138wleGYa8gl2EP8ZttqoQll52kK1FqJA2Y1SHKh-r8CTZfMqUrhgPpv12ixQ53_-2O3Uv2vYVBR6NXOkyCOuq7R3emsEH7x7DnrMjgojMFS1ysh02ZfxM4rQQa8UhcxlnnmievnXl55dESErXQ787HwIjkQIRbEZXxm1Dj-08FjIjj0_4vrt8Bv3BkTV3cDIvpPmxIna7TA-WFdEuMsy5ioNqwkYvgpRiG951ysEnXIr6wX1954G82b9FoCqLhc8EiM14%26hasRedesign%3D0%26urrMet%3Dnull%26sig%3D17f2ef9c4adafc9197193b31e502992f%26encl%3D290993138%26trkid%3D1073418&iasHash=+ItA3q3JTQkAgeMnWXbCMA==&forensiqHash=a6401be5c80d600d52eee660ec53ef95&encl=290993138&plid=5ad8fe3f7591fd6b028b456a&fid=561544a67591fda2598b4567)
> 
> If you don't want to use proxy or you don't think it makes sence just use the link like you want, else just give me you IP.

Ah wait I see the old link is tsill working *wondering.
Just use this proxy: 192.126.238.3:3128

**Comment by MacMarde** [comment]
I am an idiot I wanted to click on "comment" not on "close and comment".

**Comment by MacMarde** [comment]
@ad-m Any progress?

**Comment by ad-m** [comment]
With the use of your proxy using the given address and MANUAL performing task I can only get the following message:
![obraz](https://user-images.githubusercontent.com/3618479/61082665-38cc3700-a42a-11e9-9693-db5f3dff1141.png)

Can you catch me on Gitter ( https://gitter.im/python-anticaptcha/Lobby ), so that we can explain it efficiently? I propose 7:00 UTC 11 July 2019.

**Comment by MacMarde** [comment]
@ad-m 
Well this error message does appear often on this website. It is not necessary linked to a recaptcha solving error.

I joined gitter and wrote a message to you.

**Comment by NEOdinok** [comment]
@MacMarde @ad-m 
Have you guys solved this issue ? I'm trying to write binance bot for myself and i'm confused with how to get
"x-nft-checkbot-token" and  "x-nft-checkbot-sitekey"

**Comment by ad-m** [comment]
> I'm trying to write binance bot for myself

I am curious why do you need to handle captcha for that? Binance have official API and there is unofficial SDK: https://python-binance.readthedocs.io/en/latest/
