### ISSUE TITLE
sToken in tasks.py

### ISSUE THREAD

**Issue by taktechOne** [ad-m/python-anticaptcha#4]
```
class NoCaptchaTaskProxylessTask(BaseTask):
    type = "NoCaptchaTaskProxyless"
    websiteURL = None
    websiteKey = None
    websiteSToken = None

    def __init__(self, website_url, website_key, website_s_token=None):
        self.websiteURL = website_url
        self.websiteKey = website_key
        self.websiteSToken = website_s_token

    def serialize(self):
        return {'type': self.type,
                'websiteURL': self.websiteURL,
                'websiteKey': self.websiteKey,
                'websiteSToken': self.websiteSToken or []}
```

Change to:

```
class NoCaptchaTaskProxylessTask(BaseTask):
    type = "NoCaptchaTaskProxyless"
    websiteURL = None
    websiteKey = None

    def __init__(self, website_url, website_key):
        self.websiteURL = website_url
        self.websiteKey = website_key

    def serialize(self):
        return {'type': self.type,
                'websiteURL': self.websiteURL,
                'websiteKey': self.websiteKey
        }
```

**Comment by ad-m** [comment]
@taktechOne , why do you want drop ``websiteSToken``? ``websiteSToken`` is secret token for previous version of Recaptcha (now deprecated). Use of this field is optional, but you can not exclude pages that will still be used. Since there is the possibility that the pages of this code require, and do not interfere with the current mechanisms then I see no reason to change. I emphasize that this field is optional in ``python-anticaptcha``.

**Comment by taktechOne** [comment]
Because it breaks anti-captcha :P

**Comment by ad-m** [comment]
@taktechOne , oh, actually! Probably some changes have taken place! I'll release a new version for the moment, which fixes it!

**Comment by ad-m** [comment]
@taktechOne , new version released. Use ``pip install python-anticaptcha==0.1.1``. 

I need to work on proactive detection of such errors. Such situations should not occur.

**Comment by ad-m** [comment]
I've made the expected changes (478925347633a969e9973db7c5c80ed05c825d75). In addition, I introduced automated testing for code examples was working (#5). This should prevent such situations in the future.

I care about the correct functioning of the library. I am open to any suggestion of its development. I may also develop other tools based on it, eg specific to some other service.
