### ISSUE TITLE
createTaskSmee && Proxies

### ISSUE THREAD

**Issue by VeNoMouS** [ad-m/python-anticaptcha#40]
Should this not use the already existing requests session to inherit things such as proxies...

https://github.com/ad-m/python-anticaptcha/blob/6066e58ad803e73b3fd8e4cd729449e1b5741441/python_anticaptcha/base.py#L112-L116

**Comment by ad-m** [comment]
You are right. I will fix that today & release patch version.

**Comment by ad-m** [comment]
Issues fixed in 0.4.1 (see changelog https://python-anticaptcha.readthedocs.io/en/latest/changes.html#id1 ), so I am going to to close that issues.
