### ISSUE TITLE
explanation about solve text captcha

### ISSUE THREAD

**Issue by achikamor** [ad-m/python-anticaptcha#48]
First of all thank you very much for sharing your code!   
I have few questions about how to use your text captcha solver,  your example is :
"from python_anticaptcha import AnticaptchaClient, ImageToTextTask
api_key = '174faff8fbc769e94a5862391ecfd010'
captcha_fp = open('examples/captcha_ms.jpeg', 'rb')
client = AnticaptchaClient(api_key)
task = ImageToTextTask(captcha_fp)
job = client.createTask(task)
job.join()
print job.get_captcha_text()"

1) what should I write in api_key?  is it gonna be like the example exactly?
2) what should I write in the open() command , what is this 'example', should I download the photo of the text to solve it?
3) is the printing statement would print eventually the text that written in the image?

thanks in advance!

**Comment by ad-m** [comment]
Is there anything how I could help you?
