### ISSUE TITLE
onSuccess is not defined

### ISSUE THREAD

**Issue by Iggnacy** [ad-m/python-anticaptcha#51]
I try to use this library on https://nakedcph.com, when script tries to send solved captcha i get this error: "selenium.common.exceptions.JavascriptException: Message: javascript error: onSuccess is not defined", what is onSuccess on this site then, and how to find it?

**Comment by ad-m** [comment]
It's specific to target website. At weekend I will try to provide solution for  https://nakedcph.com.

**Comment by ad-m** [comment]
Hello,

This screen with captcha comes from CloudFlare, however it uses its own page layout (https://blog.cloudflare.com/new-feature-customize-your-cloudflare-challen/).

I would like recommend use [cloudscraper](https://github.com/VeNoMouS/cloudscraper), because it's well-maintaned (by @VeNoMouS) library designed to bypass Cloudflare security. It have support for ```python-anticaptcha``` integration.

Everything what you need is:

```python

import cloudscraper
import os
scraper = cloudscraper.create_scraper(
  interpreter='nodejs',
  recaptcha={
    'provider': 'anticaptcha',
    'api_key': os.environ['KEY']
  }
)

print(scraper.get('https://nakedcph.com/').text)
```

Let me know if this is a full solution to your problem.

**Comment by VeNoMouS** [comment]
@ad-m this could related to something we are witnessing over the past 24hrs.. after solving, getting 502 error back from cloudflare / webserver ... I have to investigate..

**Comment by ad-m** [comment]
That issue was about invalid injecting token for Recaptcha / HCaptcha. It is not something new.

I used it on now and I don't notice any issues.

**Comment by VeNoMouS** [comment]
ah is it?! we were experiencing it all last night

**Comment by ad-m** [comment]
I don't notice this issue. If I will hit that issue I will not able to provide a snippet of code.

I suggest setup daily integration test (monitoring) similiar to https://github.com/ad-m/python-anticaptcha/actions?query=event%3Aschedule+workflow%3A%22E2E+test+%E2%86%94%EF%B8%8F%22 to verify current status of integration.

**Comment by Iggnacy** [comment]
Hey, I opened this issue, on February, when it used recaptcha. Now it uses hcaptcha, so all you have to do to pass challenge is to submit hcaptcha form after changing h-captcha-response and re-captcha-response values to token received from anticaptcha API. Submitting hcaptcha is best described in [2captcha api documentation](https://2captcha.com/2captcha-api#solving_hcaptcha). Also I don't know why, but sometimes, to pass challenge you have to submit CAPTCHA more than once.
