### ISSUE TITLE
Find sitekey

### ISSUE THREAD

**Issue by Crackde** [ad-m/python-anticaptcha#70]
Hello
I'm trying to get site key from 
https://siptv.app/mylist/
I find this key from the link
6LdZsJsUAAAAAJaM1WOM8XghXQ9JETBPGftJ0mhE
in this link
https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LdZsJsUAAAAAJaM1WOM8XghXQ9JETBPGftJ0mhE&co=aHR0cHM6Ly9zaXB0di5hcHA6NDQz&hl=es-419&v=JPZ52lNx97aD96bjM7KaA0bo&theme=light&size=normal&cb=5m3zslns1v40

but when I'm injecting the result the box didn't checked

driver.execute_script("document.getElementById('recaptcha-token').value='{}';".format(response))
but i find 
when i click manually the checbox appear this

<div class="captcha_input"></div>.
<input type="hidden" name="g-recaptcha-token" value="03AGdBq27EItXYFezLsFLkgkpHS9SAOZAryXk8DGSRDOSp8F-cJ4HgmR9doWy94ob6DL9cs2Kq2NqxmVr64np5OOeI3FyXEC-mN63EKxxPlQGCQwHT2i9aIQLR2KgK3No2z1k3bpXv01SdgCwr4zLYH8tesupPbJg0mtgwX4rkz14AnD1yFLQb2u2wzRvc90dosZ62ayQI-kgDbM58C1SuC9DdU8OUQhmDMzJoqFah3Kq9SZkf918M6isgayHHxUhiZKMvmN9XbPvQNpkDukXEAS5jmG0hshqFG7c-KHod0MWCcHYndfufwEOc3Et47XlaGOaM5ESAwAwZRK0VsY2hWyWV6meFI-Mu5TUTMpvFfUG5mtZYrL--IIkAGfQvGuzpJWdjqkDFmOw4">

I don't know more
pls help me

**Comment by ad-m** [comment]
It is not important whether the checkbox is selected (this is only the appearance of the form), and whether after sending the form the expected data will be sent to the destination server. You must send the form correctly and the task will be completed.

Analyze that example: https://github.com/ad-m/python-anticaptcha/blob/master/examples/recaptcha_selenium.py

**Comment by ad-m** [comment]
Answer provided. No following response. Going to close. Le'ts me know if you have still issue how to use library.
