### ISSUE TITLE
Support for ReCaptcha Enterprise?

### ISSUE THREAD

**Issue by Psycho-Ray** [ad-m/python-anticaptcha#97]
Hello o/

Could you please add support for ReCaptcha Enterprise to this library?

Ref: https://anti-captcha.com/faq/494_everything_about_recaptcha_enterprise

**Comment by ad-m** [comment]
New package published - https://github.com/ad-m/python-anticaptcha/releases/tag/v1.0.0

**Comment by hhslepicka** [comment]
Thank you, @ad-m
